### ISSUE TITLE
scrollup UI element overlaps content on narrow displays

### ISSUE THREAD

**Issue by dantefromhell** [GreenMeteor/scrollup#20]
When a narrow display is used (reproducible on desktop browser by reducing window width), the Space menu flips to a horizontal line, empty horizontal space disappear to allow for a wider content display.

The scrollup UI is not changing behaviour though and is therefore overlapping existing content.
![image](https://github.com/GreenMeteor/scrollup/assets/90508808/ac933287-471f-4cc0-b256-df0f50339bad)

Would it be possible that the scrollup converts to a horizontal bar, located on the bottom of the screen when the display/ window is narrow?

### Steps to reproduce

1. HumHub 1.14.1 + Extensions

- scrollup
- clean theme

2. Default configuration for scrollup module
3. Scroll down in longer list (e.g. Task module)
4. Gradually change the browser window width to observer layout changes

Confirmed/ reproducible in Chrome based Browers

**Comment by ArchBlood** [comment]
Another issue that I've found is that  `#wallStream` now no longer works. :thinking:

**Comment by ArchBlood** [comment]
@dantefromhell please manually apply #21 and clear your `/path-to-humhub/assets folder and allow your assets to recompile to see if this fixes the issue, otherwise there is no complete fix for this issue. :thinking:
